# Generated by Django 2.2.5 on 2020-04-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDCountry', models.IntegerField(null=True)),
                ('Country', models.CharField(max_length=200)),
                ('CountryEng', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDTeam', models.IntegerField()),
                ('Team', models.CharField(max_length=200)),
                ('TeamEng', models.CharField(max_length=200, null=True)),
                ('IDCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='sport.Country')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDLeague', models.IntegerField()),
                ('League', models.CharField(max_length=200)),
                ('IDLeagueType', models.IntegerField()),
                ('LeagueEng', models.CharField(max_length=200)),
                ('LeagueCurrentSource', models.CharField(max_length=200)),
                ('IDCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='sport.Country')),
            ],
        ),
    ]
