# Generated by Django 2.2.5 on 2020-04-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season', models.CharField(max_length=20)),
                ('IsCurrentSeason', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDSport', models.IntegerField()),
                ('Sport', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='league',
            name='League',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=30)),
                ('Season', models.CharField(max_length=30)),
                ('League', models.CharField(max_length=30)),
                ('TypeTour', models.CharField(max_length=30)),
                ('LastTours', models.IntegerField()),
                ('TourNumber', models.IntegerField()),
                ('TourDate', models.DateTimeField()),
                ('Position', models.IntegerField()),
                ('Team', models.CharField(max_length=30)),
                ('CountGames', models.IntegerField()),
                ('CountWin', models.IntegerField()),
                ('CountDraw', models.IntegerField()),
                ('CountLose', models.IntegerField()),
                ('GoalWin', models.IntegerField()),
                ('GoalLose', models.IntegerField()),
                ('GoalDifference', models.CharField(max_length=30)),
                ('CountPoint', models.IntegerField()),
                ('CountGamesHome', models.IntegerField()),
                ('CountWinHome', models.IntegerField()),
                ('CountDrawHome', models.IntegerField()),
                ('CountLoseHome', models.IntegerField()),
                ('GoalWinHome', models.IntegerField()),
                ('GoalLoseHome', models.IntegerField()),
                ('GoalDifferenceHome', models.CharField(max_length=30)),
                ('CountPointHome', models.IntegerField()),
                ('CountGamesGuest', models.IntegerField()),
                ('CountWinGuest', models.IntegerField()),
                ('CountDrawGuest', models.IntegerField()),
                ('CountLoseGuest', models.IntegerField()),
                ('GoalWinGuest', models.IntegerField()),
                ('GoalLoseGuest', models.IntegerField()),
                ('CountPointGuest', models.IntegerField()),
                ('GoalDifferenceGuest', models.CharField(max_length=30)),
                ('IDCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stands_country', to='sport.Country')),
                ('IDLeague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stands_league', to='sport.League')),
                ('IDSeason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stands_season', to='sport.Season')),
                ('IDSport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stands_sport', to='sport.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=20)),
                ('Season', models.CharField(max_length=20)),
                ('League', models.CharField(max_length=30)),
                ('Tour', models.IntegerField()),
                ('MatchDate', models.DateTimeField()),
                ('TeamHome', models.CharField(max_length=200)),
                ('TeamGuest', models.CharField(max_length=200)),
                ('GoalHome', models.IntegerField()),
                ('GoalGuest', models.IntegerField()),
                ('IDResultType', models.IntegerField()),
                ('GoalHomePenalty', models.IntegerField()),
                ('GoalGuestPenalty', models.IntegerField()),
                ('LastDate', models.DateTimeField()),
                ('IDCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_country', to='sport.Country')),
                ('IDLeague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_league', to='sport.Season')),
                ('IDSeason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_season', to='sport.Season')),
                ('IDTeamGuest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_guest', to='sport.Team')),
                ('IDTeamHome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results_home', to='sport.Team')),
            ],
        ),
    ]
