# Generated by Django 2.2.5 on 2020-04-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20200405_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='LastDate',
            new_name='LastUpdate',
        ),
    ]
