# Generated by Django 2.2.5 on 2020-04-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_auto_20200405_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='GoalGuest',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='GoalGuestPenalty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='GoalHome',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='GoalHomePenalty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='MatchDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Tour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='LastTours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='TourDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='TourNumber',
            field=models.IntegerField(null=True),
        ),
    ]
