# Generated by Django 2.2.5 on 2020-04-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_auto_20200405_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='LastUpdate',
            field=models.DateTimeField(null=True),
        ),
    ]
