# Generated by Django 2.2.5 on 2020-04-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_auto_20200409_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='IDTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stands_team', to='sport.Team'),
        ),
    ]
