# Generated by Django 3.0.5 on 2020-04-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_standing_idteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='IsPrimary',
            field=models.IntegerField(null=True),
        ),
    ]
