# Generated by Django 3.0.5 on 2020-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0011_standing_postype'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='LastGames',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='standing',
            name='Sport',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
