# Generated by Django 3.0.5 on 2020-05-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0014_auto_20200504_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ImgSmall',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='ImgBig',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
