# Generated by Django 3.0.5 on 2020-05-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0015_auto_20200505_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='CountryEng',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
