# Generated by Django 3.0.5 on 2020-05-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0017_sport_sporteng'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='LeagueImgSrc',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
