# Generated by Django 3.0.5 on 2020-05-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0018_league_leagueimgsrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='LeagueCurrentSource',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
