# Generated by Django 3.0.5 on 2020-05-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0020_country_ismain'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='IDSeasonType',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='IDSeasonType',
            field=models.IntegerField(null=True),
        ),
    ]
