# Generated by Django 3.0.5 on 2020-05-29 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0021_auto_20200522_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='IDSport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results_sport', to='sport.Sport'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sport', models.CharField(max_length=30, null=True)),
                ('Country', models.CharField(max_length=20)),
                ('Season', models.CharField(max_length=20)),
                ('League', models.CharField(max_length=30)),
                ('Tour', models.IntegerField(null=True)),
                ('MatchDate', models.DateTimeField(null=True)),
                ('TeamHome', models.CharField(max_length=200)),
                ('TeamGuest', models.CharField(max_length=200)),
                ('GoalHome', models.IntegerField(null=True)),
                ('GoalGuest', models.IntegerField(null=True)),
                ('PredictHome', models.IntegerField(null=True)),
                ('PredictGuest', models.IntegerField(null=True)),
                ('ProdHome', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('ProdDraw', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('ProdGuest', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('PredictType', models.IntegerField()),
                ('GoalHomePenalty', models.IntegerField(null=True)),
                ('GoalGuestPenalty', models.IntegerField(null=True)),
                ('DateCreate', models.DateTimeField(null=True)),
                ('IDCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_country', to='sport.Country')),
                ('IDLeague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_league', to='sport.League')),
                ('IDResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_country', to='sport.Result')),
                ('IDSeason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_season', to='sport.Season')),
                ('IDSport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_country', to='sport.Sport')),
                ('IDTeamGuest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_guest', to='sport.Team')),
                ('IDTeamHome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict_home', to='sport.Team')),
            ],
        ),
    ]
