# Generated by Django 3.0.5 on 2020-05-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0022_auto_20200529_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predict',
            name='GoalGuestPenalty',
        ),
        migrations.RemoveField(
            model_name='predict',
            name='GoalHomePenalty',
        ),
    ]
