# Generated by Django 3.0.5 on 2020-05-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0024_auto_20200529_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predict',
            old_name='ProdDraw',
            new_name='ProbDraw',
        ),
        migrations.RenameField(
            model_name='predict',
            old_name='ProdGuest',
            new_name='ProbGuest',
        ),
        migrations.RenameField(
            model_name='predict',
            old_name='ProdHome',
            new_name='ProbHome',
        ),
    ]
